import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { FormEvent } from "react"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  const handleFormSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()

    console.log(";dasdoifjd")

    const formData = new FormData(e.currentTarget)

    console.log(formData.get("address"))
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Localnet NFTs config generator</h1>
        <p className={styles.description}>
          Get started by entering a wallet address:{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        Why?
        <div className={styles.grid}>
          <ul>
            <li>
              Working on Localnet is 100x faster, but you always need to clone
              the accounts to the validator
            </li>
            <li>
              {" "}
              This app will clone all accounts from a wallet address, and parse
              into toml format.
            </li>
            <li>
              All you need to do is to copy the lines and paste into your
              Anchor.toml file
            </li>
          </ul>
        </div>
        <form onSubmit={handleFormSubmit}>
          <label>
            Wallet address:
            <input
              name="address"
              value="FhHV2jmbPw4guEGhkDfFJiYLeUcMzTmYr6GPk9TuKTE"
            />
          </label>
          <label>
            Network:
            <select>
              <option value="1">Mainnet</option>
              <option value="2">Devnet</option>
            </select>
          </label>
          <button type="submit">Generate Anchor.toml!</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
